version: '3'

services:
  redis:
    image: 'redis:latest'
    container_name: 'smartcrm-redis'
    ports:
      - "6379:6379"

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'smartcrm-backend-worker'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    command: "yarn dev"

  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'smartcrm-frontend-web'
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: "yarn dev"

volumes:
  redis_data:
    name: smart-outreach-redis-data 
